oracle/netsuite-suitecloud-sdk

src/services/EnvironmentInformationService.js

Fix java version check to accept openjdk

PDPDEVTOOL-2134 Fixes #12

---

src/metadata/ObjectTypesMetadata.js

Adding Bank Parser Plugin and FIConnectivityPlugin to the object types metadata

feature/PDPDEVTOOL-2095: Add Bank Parser Plugin and FIConnectivityPlugin objects

---

README.md

I didn't mention the 19.2 version. Should I? If so, what NPM version should I give it?

Edited README.md to include changes for the 20.1 release

---

packages/node-cli/src/services/FileCabinetService.js

Fix bug wherein child folders are not shown for selection

Fix bug wherein child folders are not shown for selection

---

packages/node-cli/src/commands/outputFormatters/DeployOutputFormatter.js

PDPDEVTOOL-3108: Fix wrong message when content protection is applied for deploy

PDPDEVTOOL-3108: Fix wrong message when content protection is applied for deploy

---

packages/vscode-extension/package.json

Update typescript version in vscode-extension to sync with OSSR approval

update typescript to 3.8.3 in vscode-extension

---

packages/node-cli/src/metadata/CommandGenerators.json

fix files:list command generator file reference

bugfix: listfiles command

---

packages/node-cli/src/core/extensibility/CLIConfigurationService.js

Fix suitecloud.config.js "unhandled exception" message

bugfix/pdpdevtool-1685: fix suitecloud.config.js error message

---

packages/node-cli/src/commands/file/import/ImportFilesAction.js

fix: any possible error thrown in the process is now constructing a proper ActionResult.

bugfix/pdpdevtool-3724 file:import from a suiteapp project

---

packages/node-cli/src/commands/project/create/CreateProjectOutputHandler.js
packages/node-cli/src/services/actionresult/CreateProjectActionResult.js

fix action result construction for create project
realted to npmPackageInitialized value

bugfix/pdpdevtool-3730 createproject with unit-testing error message

---

packages/unit-testing/README.md

Fixed indentation problems in a numbered list for npm publishing

SuiteCloud Unit Testing README.md file edited

---

packages/vscode-extension/messages.json
packages/vscode-extension/src/commands/ManageAccounts.ts

Logged the success message & display it in a pop-up window

feature/PDPDEVTOOL-3757-VSCode-account:setup-improve-output

---

extensions/localserver-cli-command/package.json

handlebars and node-watch update

Update package.json fix #115

---

extensions/localserver-cli-command/package-lock.json

package.lock.json needs to be in synced with package.json so that our publishing build will be successful.

localserver-cli-command-update-package-lock-json

---

package-lock.json
package.json
packages/node-cli/package-lock.json
packages/node-cli/package.json
packages/unit-testing/package-lock.json
packages/unit-testing/package.json

This is basically the same with https://github.com/oracle/netsuite-suitecloud-sdk/pull/234 (PDPDEVTOOL-3744-Update-3rd-party-libs-for-SuiteCloud-SDK-project-in-GitHub). This is just merging the same changes to the release/20.2 branch.

PDPDEVTOOL-3744-Update-3rd-party-libs-for-SuiteCloud-SDK-project-in-GitHub

---

packages/vscode-extension/src/commands/ManageAccounts.ts
packages/vscode-extension/src/core/SuiteCloudRunner.ts
packages/vscode-extension/src/core/sdksetup/SdkProperties.ts
packages/vscode-extension/src/core/sdksetup/SdkServices.ts
packages/vscode-extension/src/core/sdksetup/extension.config.json

improvement-to-vscode-extension-build-and-dependencies

---

packages/vscode-extension/src/commands/BaseAction.ts
packages/vscode-extension/src/commands/ManageAccounts.ts
packages/vscode-extension/src/core/SuiteCloudRunner.ts
packages/vscode-extension/src/loggers/VSConsoleLogger.ts

Running multiple commands one after another makes the output messy

PDPDEVTOOL-3872

---

packages/node-cli/src/commands/object/import/ImportObjectsAction.js

Quote --destinationfolder in importobjects

bugfix/pdpdevtool 3880 : importobjects non-interactive

---

.gitignore
packages/vscode-extension/messages.json

Added coverage reports to .gitignore

Change message word.

---

packages/vscode-extension/src/commands/BaseAction.ts
packages/vscode-extension/src/commands/CreateProject.ts
packages/vscode-extension/src/service/MessageService.ts

Bugs Fixed:
- PDPDEVTOOL-4321: Can't create project when no workspace is open
- PDPDEVTOOL-4323: Wrong Message

Bug Fix - PDPDEVTOOL-4321, PDPDEVTOOL-4323

---

packages/vscode-extension/src/commands/BaseAction.ts
packages/vscode-extension/src/commands/CreateProject.ts
packages/vscode-extension/src/service/MessageService.ts

Applying same changes merged to dev branch to release/21.2 branch
- PDPDEVTOOL-4321: Can't create project when no workspace is open
- PDPDEVTOOL-4323: Wrong Message

Apply changes from dev branch - PDPDEVTOOL-4321, PDPDEVTOOL-4323

---

packages/node-cli/src/commands/file/create/CreateFileAction.js
packages/node-cli/src/utils/CommandUtils.js

Removes the extra "" added to the output message.

fix shown output for CreateFileAction.js

---

packages/node-cli/src/utils/AuthenticationUtils.js
packages/vscode-extension/src/commands/SetupAccount.ts

showing error in Setup Account command when jar is corrupted

PDPDEVTOOL-4387 showing error in Setup Account command

---

packages/vscode-extension/src/commands/CreateProject.ts

removing trailing spaces in ACP projects folder name creation

PDPDEVTOOL-4444 removing trailing spaces in ACP projects folder name

---

package-lock.json
packages/node-cli/package-lock.json
packages/node-cli/package.json
packages/unit-testing/package-lock.json
packages/unit-testing/package.json
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

updating versions in package.json s
updating package-lock.json (no proxy used)
change node-cli dependency version for vscode extension

pre-publish/21.2: bump version before publishing

---

packages/vscode-extension/README.md

Hello, fixing wrong headings, @antoniofruci @karl-anthony-ng can you kindly review it?

Fixing wrong headings

---

package.json
packages/node-cli/package-lock.json
packages/node-cli/package.json
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

update suitecloud-cli version
upadate suitecloud-vscode-extension dependency on suitecloud-cli
using new release sdk.jar

bump cli to 1.3.2 version

---

packages/node-cli/src/ApplicationConstants.js

This reverts commit 99c77848d474ea36be30a65be1e4fc681853f4c9.

Revert "updatate refrence to future Netsuite version"

---

packages/vscode-extension/README.md
packages/vscode-extension/package.json

remove shortcuts from README.md

fix windows deploy shortcut

---

packages/node-cli/README.md

Add update in object update command

Add update in object update command

---

packages/vscode-extension/README.md

Documentation changes for validate project

---

packages/node-cli/src/core/sdksetup/SdkLicense.js
packages/node-cli/src/utils/http/ProxyAgent.js

PDPDEVTOOL-4753 remove read-only and handle proxy error

---

packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

update package.json and package-lock.json

bump version in vscode-extension

---

packages/unit-testing/jest-configuration/SuiteCloudJestConfiguration.js
packages/unit-testing/package.json
packages/unit-testing/stubs/crypto/certificate/certificate.js
packages/unit-testing/stubs/currentRecord/CurrentRecordInstance.js
packages/unit-testing/stubs/currentRecord/currentRecord.js
packages/unit-testing/stubs/query/RelativeDate.js
packages/unit-testing/stubs/task/accounting/recognition/recognition.js
packages/unit-testing/stubs/translation/translation.js
packages/unit-testing/stubs/ui/dialog/dialog.js
packages/unit-testing/stubs/workbook/MeasureSort.js
packages/unit-testing/stubs/workbook/ReportStyleRule.js
packages/unit-testing/stubs/workbook/Section.js
packages/unit-testing/stubs/workbook/Style.js
packages/unit-testing/stubs/workbook/Table.js
packages/unit-testing/stubs/workbook/workbook.js

Found inconsistencies while creating tests for the stubs.

bugfix/pdpdevtool-5028: suitescript 2.0 manual stubs tests

---

packages/node-cli/package.json
packages/node-cli/src/templates/unittest/package.json.template

update node-cli/package.json
update unittesting package.json.template

Fix download jar reference and minor version details

---

package-lock.json
packages/node-cli/package.json
packages/vscode-extension/CHANGELOG.md

Update xml2j
Update package.json
Update package-lock.json

PDPDEVTOOL-5147: U3 issue 715716

---

package-lock.json
packages/node-cli/package.json

Update version vm2 to 3.9.17, bump cli to 1.7.2

Fix vm2 vulnerability

---

README.md
THIRD_PARTY_LICENSES.txt
package-lock.json
packages/node-cli/README.md
packages/node-cli/package.json
packages/node-cli/src/core/extensibility/CLIConfigurationService.js
packages/node-cli/src/services/NpmInstallRunner.js
packages/unit-testing/README.md
packages/vscode-extension/README.md

Remove vm2 dependency and usage, fix fails when creating new project with unit testing support (PDPDEVTOOL-5113), changes in README files

Prepare release

---

package-lock.json
packages/unit-testing/jest-configuration/SuiteCloudJestConfiguration.js
packages/unit-testing/package.json
packages/unit-testing/stubs/commerce/webstore/shopper.js
packages/unit-testing/stubs/workbook/Pivot.js

fix unit-testing wrong imports
related to issue 751

bugfix/pdpdevtool-5310: fix unit-testing wrong imports

---

packages/vscode-extension/src/commands/CreateFile.ts
packages/vscode-extension/src/commands/UploadFile.ts

This pull request fixes https://github.com/oracle/netsuite-suitecloud-sdk/issues/711

vscode-extension fix for issue 711

---

packages/node-cli/src/commands/account/manageauth/ManageAccountOutputHandler.js
packages/node-cli/src/utils/AccountCredentialsFormatter.js

Fix the bug about domain not being shown for dev machines when listing credentials

PDPDEVTOOL-5714 fix the bug about domain not being shown

---

packages/node-cli/src/commands/account/manageauth/ManageAccountInputHandler.js

Fix the bug about domain not being shown for dev machines when listing credentials in interactive mode

PDPDEVTOOL-5714 Fix domain not shown

---

packages/vscode-extension/CHANGELOG.md
packages/vscode-extension/package-lock.json
packages/vscode-extension/package.json

bump vscode-extension to prepare release.

feature/pdpdevtool-5825: update vscode version and changelog

---

packages/uif-types/package.json
packages/uif-types/uif/component.d.ts
packages/uif-types/uif/core.d.ts

Bugfix: UIF types are missing children prop

---

README.md

this is created to resolve conflicts from release/25.2 to master

feature/pdpdevtool 6106 resolve conflicts from release25.2 to master
